version: '3.7'
services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx/
        volumes:
            - ~/data/www:/var/www
        ports:
            - "443:443"
        networks:
            - inception
        depends_on:
            - wordpress
        restart: "unless-stopped"

    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress/
        volumes:
            - ~/data/www:/var/www
        expose:
            - "9000"
        networks:
            - inception
        depends_on:
            - mariadb
        env_file:
            - "./.env"
        restart: "unless-stopped"
  
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb/
        volumes:
            - ~/data/mariadb:/var/lib/mysql
        expose:
            - "3306"
        networks:
            - inception
        env_file:
            - "./.env"
        restart: "unless-stopped"

networks:
    inception:
